apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: prod

replicas:
- name: guestbook-ui
  count: 3

commonLabels:
  env: prod

images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newName: acrargocdgitopsprod.azurecr.io/ks-guestbook-demo
  newTag: "0.2"

