apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: REPLACE_ME_WITH_REPO_URL
    targetRevision: HEAD
    path: environments/placeholder
  destination:
    server: https://kubernetes.default.svc
    namespace: placeholder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
